// <auto-generated />
using System;
using ECOO.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECOO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425164037_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECOO.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reusable Goods"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Organic Food"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eco Apparel"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zero-Waste Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Natural Beauty"
                        });
                });

            modelBuilder.Entity("ECOO.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECOO.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECOO.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Durable, BPA-free bamboo & stainless steel bottle. Keeps drinks cold for 24 hrs.",
                            ImageUrl = "/images/products/bamboo-bottle.jpg",
                            Name = "Bamboo Water Bottle",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Replace single-use plastic wrap. Reusable, washable, compostable.",
                            ImageUrl = "/images/products/beeswax-wraps.jpg",
                            Name = "Beeswax Food Wraps (3-pack)",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Ceremonial-grade matcha from shade-grown Japanese tea leaves. 100g.",
                            ImageUrl = "/images/products/matcha.jpg",
                            Name = "Organic Matcha Powder",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Extra-virgin, single-origin olive oil in a recyclable glass bottle. 500ml.",
                            ImageUrl = "/images/products/olive-oil.jpg",
                            Name = "Cold-Pressed Olive Oil",
                            Price = 12.49m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Sturdy, naturally dyed hemp bag. Holds up to 20 kg. Certified organic.",
                            ImageUrl = "/images/products/hemp-tote.jpg",
                            Name = "Hemp Tote Bag",
                            Price = 18.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Soft tee made from 100% post-consumer recycled cotton. Available S–XL.",
                            ImageUrl = "/images/products/recycled-tshirt.jpg",
                            Name = "Recycled Cotton T-Shirt",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Bamboo handle + plant-fibre bristles. Fully compostable after use.",
                            ImageUrl = "/images/products/dish-brush.jpg",
                            Name = "Compostable Dish Brush",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Set of 4 reusable straws + cleaning brush in a cotton pouch.",
                            ImageUrl = "/images/products/steel-straws.jpg",
                            Name = "Stainless Steel Straw Set",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "100% organic cold-pressed rosehip oil. Vitamin-C rich. 30ml amber glass bottle.",
                            ImageUrl = "/images/products/rosehip-oil.jpg",
                            Name = "Rosehip Face Oil",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Palm-oil-free, vegan shampoo bar. Replaces 3 plastic bottles. All hair types.",
                            ImageUrl = "/images/products/shampoo-bar.jpg",
                            Name = "Solid Shampoo Bar",
                            Price = 13.50m
                        });
                });

            modelBuilder.Entity("ECOO.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECOO.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECOO.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECOO.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECOO.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECOO.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECOO.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECOO.Domain.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
